name: default-detection
channels:
  - defaults
dependencies:
  - jupyterlab=1.2.6
  - pandas=1.2.5
  - conda-forge::hyperopt==0.2.4
  - conda-forge::category_encoders==2.1.0
  - lightgbm=3.1.1
  - scikit-learn=0.24.2
  - moto=1.3.16
  - dill=0.3.1.1
  - pip=21.0.1
  - python=3.7.7
  - boto3=1.10.22
  - flask=1.1.2
  - seaborn=0.11.1
  - paste=3.5.0
